version: "3"

services:

  mysql:
    image: mysql:8.0.27
    container_name: saledatabase
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: saledatabase
    ports:
      - "3306:3306"